class ConfigFiles():
    PRIVATE_KEY = 'P17B8JZH1PRACVEC5W4IJXH2FZKD6ZFB8T5OAEFWG7VHJE40MQ'
    DATABASE_SQLITE = 'src/database/authenticator.db'
    BRAZIL_TIME_ZONE = 'America/Sao_Paulo'
    TIME_EXPIRATION_TOKEN_IN_MINUTES = 60
    